### ISSUE TITLE
Фича: добавить "другое" в темы

### ISSUE THREAD

**Issue by shkaff** [AngryJKirk/vas3k_topics#3]
Чтобы ловить все темы, которые не попадают под список, добавить "другое", которая не привязана ни к какому чату.

**Comment by AngryJKirk** [comment]
а в какой чат то все попадать будет? @shkaff

**Comment by shkaff** [comment]
@AngryJKirk так к каналу же будет привязан чат для комментов. Вот туда и будет падать.
