### ISSUE TITLE
Баг: сообщения с <> зависают в бесконечном цикле обработки

### ISSUE THREAD

**Issue by marinegor** [AngryJKirk/vas3k_topics#42]
Если в тексте сообщения есть <>, то бот бесконечно просит добавить хештеги, не присылает превьюшку получившегося сообщения и в целом тупит.
При этом в самом формате сообщения нет указания на то, что нельзя иметь `<` или `>` в тексте сообщения.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/20686002/221587519-c94c4662-87f5-4830-9e12-208f2451915e.png">
<img width="650" alt="image" src="https://user-images.githubusercontent.com/20686002/221587530-a2d1ce8f-7465-4f48-b2f5-b7d55f3d7692.png">
<img width="647" alt="image" src="https://user-images.githubusercontent.com/20686002/221587541-25f5473e-87bf-4975-9262-22a00b2a039e.png">
<img width="650" alt="image" src="https://user-images.githubusercontent.com/20686002/221587555-6d011eb4-cbd3-44c1-b71c-f0d5065a44c5.png">

**Comment by AngryJKirk** [comment]
Починено
