### ISSUE TITLE
Фича: текст с пояснением про "хорошие вопросы"

### ISSUE THREAD

**Issue by shkaff** [AngryJKirk/vas3k_topics#7]
После /start выдавать сообщением общие правила про то, какие вопросы хорошие, какие нет (я могу сделать текст, если будет, куда, я сходу побоялся сломать).

**Comment by AngryJKirk** [comment]
@shkaff напиши текст, пожалуйста и закинь сюда, я добавлю

**Comment by shkaff** [comment]
ℹ️ Твой вопрос появится в канале _link_ и будет направлен в подходящий чат.

📰 **Заголовок должен сразу давать понять суть**, а не заигрывать с аудиторией.

📝 **Формулируй вопрос как можно точнее.** Правильный вопрос - половина ответа. Расскажи, что ты уже пробовал, и что не получилось.

🈶 **Не пользуйся сленгом,** это поможет лучше тебя  понять.

#️⃣ **Используй теги:** это поможет в навигации. Проставь 2-4 тега в конце вопроса.

❗️Тут действуют все [правила Клуба](https://vas3k.club/docs/about/).
