### ISSUE TITLE
Баг: тема попала в заголовок

### ISSUE THREAD

**Issue by shkaff** [AngryJKirk/vas3k_topics#8]
Получилось что-то странное. Я хотел изменить заголовок, а бот предложил мне сменить тему. Когда я выбрал тему, он добавил этот текст в заголовок. См. ниже (я только кликал кнопки, ничего не писал)
<img width="670" alt="Screenshot 2022-03-20 at 19 40 23" src="https://user-images.githubusercontent.com/2661956/159177466-2ee59376-e34b-4554-aee1-1f3f832a4a75.png">

**Comment by AngryJKirk** [comment]
Починил
